---
title: "Acceso a vacunación por distritos en Perú"
author: "Brian Peña-Calero"
date: "01/09/2021"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    number_sections: yes
    highlight: kate
    theme: flatly
    code_folding: hide
    toc_depth: 3
    code_download: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# devtools::install_github("jmcastagnetto/ubigeo")
library(sf)
sf_use_s2(FALSE)

```
# Importación de datos

```{r}
centros_vacunacion <- read_csv("1. Data/TB_CENTRO_VACUNACION.csv")
tb_ubigeo <- read_csv("1. Data/TB_UBIGEOS.csv")
ubigeo_distrito <- ubigeo::ubigeo_district
# poblacion <- read_csv("1. Data/TB_POBLACION_INEI.csv")
# poblacion <- read_rds("1. Data/poblacion_inei_2017.rds")
poblacion <- read_rds("1. Data/poblacion_inei_2017_detailed.rds")
vacunas <- read_csv("../Data General/vacunas_covid.csv")
peru_shp <- lis::Peru
```

# Formato de datos

## Formato de data individual
Calcular grupos de edades *frecuentes* para hacer la comparación con población vacunada.
```{r}
poblacion <- poblacion %>%
  rowwise() %>% 
  mutate(
    across(edad_0:edad_115_anos, as.numeric),
    `12-17` = sum(c_across(edad_8_anos:edad_13_anos)),
    `18-29` = sum(c_across(edad_14_anos:edad_25_anos)),
    `30-49` = sum(c_across(edad_26_anos:edad_45_anos)),
    `50-59` = sum(c_across(edad_46_anos:edad_55_anos)),
    `60a+`  = sum(c_across(edad_56_anos:edad_115_anos))
  ) %>% 
  ungroup() %>% 
  select(ubigeo:distr, `12-17`:`60a+`)
```

```{r}
poblacion_ubigeo <- ubigeo_distrito %>% 
  filter(district != "SANTA MARIA DE HUACHIPA", # No es considerado un distrito
         reniec != "170107") %>% # Quitar el nuevo distrito de San Antonio
  select(department:district, ubigeo = inei) %>% 
  rename(
    DEPARTAMENTO = department,
    PROVINCIA = province,
    DISTRITO = district
  ) 
  

poblacion_lis <- peru_shp %>% 
  as_tibble() %>% 
  select(reg, prov, distr, ubigeo) %>% 
  rename(
    DEPARTAMENTO = reg,
    PROVINCIA = prov,
    DISTRITO = distr
  )

new_districts <- poblacion_ubigeo %>% 
  anti_join(
    poblacion_lis,
    by = c("ubigeo")
  )

poblacion_ubigeo <- poblacion_ubigeo %>%  # Nos quedamos solo con los
  filter(!ubigeo %in% new_districts$ubigeo) # 1874 distritos
```



```{r}
poblacion_tidy <- poblacion %>% 
  select(-c(reg, prov, distr)) %>% 
  full_join(
    poblacion_ubigeo,
    by = "ubigeo"
  ) %>% 
  # select(-c(ubigeo)) %>% 
  pivot_longer(
    cols = c(`12-17`:`60a+`),
    names_to = "Grupo_Edad",
    values_to = "N"
  )
```


```{r}
summ_vacunas <- vacunas %>% 
  mutate(
    Grupo_Edad = case_when(
      EDAD >= 60 ~ "60a+",
      EDAD >= 50 ~ "50-59",
      EDAD >= 30 ~ "30-49",
      EDAD >= 18 ~ "18-29",
      EDAD >= 12 ~ "12-17",
      TRUE ~ "Sin registro"
    )
  ) %>% 
  count(DEPARTAMENTO, PROVINCIA,
        DISTRITO, Grupo_Edad, DOSIS) %>% 
  mutate(
    DISTRITO = ifelse(DISTRITO == "CORONEL GREGORIO ALBARRACIN LANCHIP",
                      "CORONEL GREGORIO ALBARRACIN LANCHIPA",
                      DISTRITO)
  )
```


```{r}
centros_vacunacion_format <- centros_vacunacion %>% 
  left_join(
    tb_ubigeo %>% 
      select(id_ubigeo, ubigeo_inei:macroregion_minsa), 
    by = "id_ubigeo"
  ) %>% 
  left_join(
    ubigeo_distrito %>% 
      select(ubigeo_inei = inei, pop_density_2020,
             food_vulnerability_index:extreme_poverty_pct),
    by = "ubigeo_inei"
  ) %>% 
  mutate(
    distrito = ifelse(distrito == "CORONEL GREGORIO ALBARRACIN LANCHIP",
                      "CORONEL GREGORIO ALBARRACIN LANCHIPA",
                      distrito)
  )
```

## Crear conjuntos de datos

```{r}
estate_vacunas <- summ_vacunas %>% 
  filter(Grupo_Edad != "Sin registro",
         DOSIS == 2) %>% 
  select(-DOSIS) %>% 
  full_join(
    poblacion_tidy 
  ) %>% 
  mutate(
    # n = replace_na(n, 0),
    Avance = n/N,
    Niv_Avance = case_when(
      Avance <= 0.1 ~ "Hasta 10%",
      Avance <= 0.3 ~ "11 a 30%",
      Avance <= 0.5 ~ "31 a 50%",
      Avance <= 0.7 ~ "50 a 70%",
      Avance <= 0.9 ~ "70 a 90%",
      Avance > 0.9 ~ "90% a +",
      TRUE ~ "Sin registro"
    ),
    Niv_Avance = factor(Niv_Avance),
    Niv_Avance = fct_relevel(Niv_Avance, "Sin registro",
                             "Hasta 10%")
  ) 
```




```{r}

estate_vacunas_2 <- summ_vacunas %>% 
  filter(Grupo_Edad != "Sin registro",
         DOSIS == 2) %>% 
  select(-DOSIS) %>% 
  full_join(
    poblacion_tidy 
  ) %>% 
  mutate(
    # n = replace_na(n, 0),
    Avance = n/N,
    Niv_Avance = case_when(
      Avance <= 0.5 & Avance >= 0.1 ~ "10 a 50%",
      Avance > 0.5 ~ "50% a +",
      TRUE ~ "0 a 10%"
    ),
    Niv_Avance = factor(Niv_Avance)
  ) 


estate_centros_vacunacion <- centros_vacunacion_format %>% 
  count(DEPARTAMENTO = departamento,
        PROVINCIA = provincia, 
        DISTRITO = distrito) %>% 
  full_join(
    poblacion_tidy
  ) %>% 
  mutate(
    Disponibilidad = (n/N)*10000,
    Cat_Disponibilidad = case_when(
      # Disponibilidad < 1 ~ "Menos de 1 centro",
      Disponibilidad >= 1 & Disponibilidad < 2 ~ "Al menos un centro",
      Disponibilidad >= 2 ~ "Más de 2 centros",
      TRUE ~ "Menos de 1 centro"
    ),
    Cat_Disponibilidad = factor(Cat_Disponibilidad),
    Cat_Disponibilidad = fct_relevel(Cat_Disponibilidad, "Menos de 1 centro")
  )  

avance_y_centros <- estate_vacunas_2 %>% 
  select(ubigeo, DEPARTAMENTO:Grupo_Edad,
         Avance, Niv_Avance) %>% 
  full_join(
    estate_centros_vacunacion %>% 
      select(ubigeo, Grupo_Edad, Disponibilidad, 
             Cat_Disponibilidad)
  ) 

avance_y_centros <- avance_y_centros %>% 
  mutate(
    Niv_tmp = case_when(
      Niv_Avance == "0 a 10%" ~ 1,
      Niv_Avance == "10 a 50%" ~ 2,
      TRUE ~ 3
    ),
    Cat_tmp = case_when(
      Cat_Disponibilidad == "Menos de 1 centro" ~ 1,
      Cat_Disponibilidad == "Al menos un centro" ~ 2,
      TRUE ~ 3 
    ),
    bi_class = paste0(Niv_tmp, "-", Cat_tmp),
    Grupo_Edad = case_when(
      Grupo_Edad == "12-17" ~ "12 a 17 años",
      Grupo_Edad == "18-29" ~ "18 a 29 años",
      Grupo_Edad == "30-49" ~ "30 a 49 años",
      Grupo_Edad == "50-59" ~ "50 a 59 años",
      Grupo_Edad == "60a+" ~ "60 años a más"
    )
  ) %>% 
  select(-c(Niv_tmp, Cat_tmp))
```




# Generación de gráfico


```{r}
peru_distr_shp <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    estate_vacunas 
  ) %>% 
  mutate(distr_lab = ifelse(Niv_Avance == "Sin registro",
                            DISTRITO, NA),
         distr_lab = str_to_title(distr_lab))

n_colors <- peru_distr_shp %>% 
  pull(Niv_Avance) %>% 
  unique() %>% 
  length()

fill_colors <- lis::lis_pal("npr", reverse = T)(n_colors)
fill_colors[1] <- "#8b8b8b"

avance_1 <- peru_distr_shp %>% 
  filter(Grupo_Edad != "12-17") %>% 
  ggplot() + 
  geom_sf(aes(fill = Niv_Avance),
          lwd = 0) +
  facet_wrap(vars(Grupo_Edad)) + 
  scale_fill_manual(
    values = fill_colors
  ) + 
  # lis::scale_fill_lis("npr",
  #                     reverse = TRUE) +
  labs(fill = "Avance de \nVacunación") +
  # geom_sf_text(aes(label = distr_lab),
  #              size = 1) +
  ggrepel::geom_text_repel(aes(label = distr_lab,
                               geometry = geometry),
                           stat = "sf_coordinates",
                           min.segment.length = 0,
                           size = 1.5,
                           force_pull = 3) + 
  theme_bw() +
  theme(
    text = element_text(
      size = 11,
      face="bold"), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.text = element_text(
      face="plain",
      colour="black",
      size=9),
    legend.title =  element_text(
      size = 11,
      face="bold",
      colour="black",
      hjust = 0.5)
  )
```

```{r}
ggsave("2. Plots/Avance Vacunación 1.png",
       avance_1,
       width = 5,
       height = 6,
       dpi = 800)
```


```{r}
avance_2 <- avance_1 + 
  theme(
    legend.position="top",
    legend.title =  element_text(size = 9.5,
                                 face="bold",
                                 colour="black",
                                 hjust = 0.5),
    legend.text = element_text(face="plain",
                               colour="black",
                               size=7.5)
  )
```

```{r}
ggsave("2. Plots/Avance Vacunación 2.png",
       avance_2,
       width = 5,
       height = 6,
       dpi = 800)
```


# Biscale plot

## General
 Testear: https://slu-opengis.github.io/biscale/articles/biscale.html

```{r}

# source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
# 
# avance_y_centros %>% 
#   select(Grupo_Edad, Niv_Avance, Cat_Disponibilidad) %>% 
#   filter(Grupo_Edad  != "12-17") %>% 
#   crosstab(.,
#            row.vars = c("Grupo_Edad", "Niv_Avance"), 
#            col.vars = "Cat_Disponibilidad", type = "f")
```

 
```{r}
library(biscale)
library(ggspatial)
library(cowplot)

fecha_update <- "23 de Septiembre"
```

```{r}
biscale_peru_shp <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12-17")

peru_dep_shp <- biscale_peru_shp %>% 
  group_by(DEPARTAMENTO) %>% 
  summarise()

biscale_plot <- biscale_peru_shp %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), lwd = 0,
          color = "white", show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  geom_sf(data = peru_dep_shp, fill = NA,
          color = "#1c0b07", lwd = 0.3) +
  facet_wrap(vars(Grupo_Edad)) + 
  scale_x_continuous(breaks = rev(seq(-70, -79, -3))) +
  annotation_scale() +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
  # bi_scale_fill(pal = custom_pal, dim = 3) +
  
```


```{r}
legend <- bi_legend(pal = "DkViolet",
                    dim = 3,
                    xlab = "+ Avance ",
                    ylab = "+ Disponibilidad ",
                    size = 10)

# bi_legend(pal = "DkViolet",
#           dim = 3,
#           xlab = "+ Avance ",
#           ylab = "+ Disponibilidad ",
#           size = 8)


# custom_pal <- bi_pal_manual(val_1_1 = "#e8e8e8", 
#                             val_1_2 = "#ecb778",
#                             val_1_3 = "#e88245",
#                             val_2_1 = "#87cdb5", 
#                             val_2_2 = "#3b9f94", 
#                             val_2_3 = "#03595c", 
#                             val_3_1 = "#95cd87", 
#                             val_3_2 = "#4d9f3b", 
#                             val_3_3 = "#0c5c03")


# a <- lis::lis_pal("npr", reverse = T)(6)
# unikn::seecol(a)
```

```{r}
final_plot <- ggdraw(biscale_plot +
                       theme(
                         plot.margin = unit(c(0, 4, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) +
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )

ggsave("2. Plots/Biscale Nacional.png",
       final_plot,
       device = png,
       width = 7.6,
       height = 8,
       dpi = 300)


title_peru <- ggdraw() + 
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19",
    size = 14,
        fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7.5, 0), "cm")
  )


subtitle_peru <- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -6, 0), "cm")
  )

biscale_title <- plot_grid(
  title_peru, 
  subtitle_peru,
  final_plot +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)

biscale_title <- ggdraw(
  add_sub(biscale_title,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
) 


biscale_title <- ggdraw(
  add_sub(biscale_title,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )


ggsave("2. Plots/Biscale Nacional con Título 300dpi.png",
       biscale_title,
       device = png,
       width = 6.2,
       height = 8.1,
       dpi = 300)

ggsave("2. Plots/Biscale Nacional con Título 800dpi.png",
       biscale_title,
       device = png,
       width = 6.2,
       height = 8.1,
       dpi = 800)

# library(patchwork)
# final2 <- biscale_plot + 
#   inset_element(
#     legend,
#     0.74, 0.3, 0.94, 0.7
#   )
# 
# ggsave("2. Plots/final2.png",
#        final2,
#        device = png,
#        width = 8,
#        height = 6,
#        dpi = 800)
```

## Por ciudades

### Lima Metropolitana y Callao


```{r}
biscale_lima <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         PROVINCIA == "LIMA" | DEPARTAMENTO == "CALLAO") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class),
          show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  scale_x_continuous(breaks = rev(seq(-76.7, -77.1, -0.2))) +
  annotation_scale() +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_lima <- ggdraw(biscale_lima +
                       theme(
                         plot.margin = unit(c(0, 3, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_lima <- ggdraw() +
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19 en \nLima Metropolitana y Callao",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -10, 0), "cm")
  )

subtitle_lima <- ggdraw() +
  draw_label(
    str_wrap("Actualizado al 23 de Septiembre del 2021."),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7.5, 0), "cm")
  )

biscale_title_lima <- plot_grid(
  title_lima, 
  subtitle_lima,
  final_plot_lima +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)


biscale_title_lima <- ggdraw(
  add_sub(biscale_title_lima,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)

biscale_title_lima <- ggdraw(
  add_sub(biscale_title_lima,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )

ggsave("2. Plots/Ciudades/1. Biscale Lima Metropolitana y Callao.png",
       biscale_title_lima,
       device = png,
       width = 6.4,
       height = 9,
       dpi = 300)
```


### Loreto

```{r}
loreto_prov_shp <- biscale_peru_shp %>% 
  filter(DEPARTAMENTO == "LORETO") %>% 
  group_by(PROVINCIA) %>% 
  summarise()
```


```{r}
biscale_loreto <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         DEPARTAMENTO == "LORETO") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), 
          show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  geom_sf(data = loreto_prov_shp, fill = NA,
          color = "#1c0b07", lwd = 0.5) +
  annotation_scale(location = "br") +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_loreto <- ggdraw(biscale_loreto +
                       theme(
                         plot.margin = unit(c(0, 3.5, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_loreto <- ggdraw() +
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19 \nen Loreto",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7, 0), "cm")
  )

subtitle_loreto <- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -5.5, 0), "cm")
  )

biscale_title_loreto <- plot_grid(
  title_loreto, 
  subtitle_loreto,
  final_plot_loreto +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)

biscale_title_loreto <- ggdraw(
  add_sub(biscale_title_loreto,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)


biscale_title_loreto <- ggdraw(
  add_sub(biscale_title_loreto,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )


ggsave("2. Plots/Ciudades/2. Biscale Loreto.png",
       biscale_title_loreto,
       device = png,
       width = 6.4,
       height = 7,
       dpi = 300)

ggsave("2. Plots/Ciudades/2. Biscale Loreto 800dpi.png",
       biscale_title_loreto,
       device = png,
       width = 6.4,
       height = 7,
       dpi = 800)
```


### Arequipa - Provincia


```{r}
biscale_arequipa <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         PROVINCIA == "AREQUIPA") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), lwd = 0,
          color = "white", show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  scale_x_continuous(breaks = rev(seq(-70.9, -72.2, -0.3))) +
  annotation_scale(location = "br") +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_arequipa <- ggdraw(biscale_arequipa +
                       theme(
                         plot.margin = unit(c(0, 3.5, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.78,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_arequipa <- ggdraw() +
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19 en la \nProvincia de Arequipa",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    panel.background = element_rect(fill = "white",
                                    colour = NA),
    plot.margin = unit(c(0, 0, -5, 0), "cm")
  )

subtitle_arequipa <- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -5.5, 0), "cm")
  )



biscale_title_arequipa <- plot_grid(
  title_arequipa, 
  subtitle_arequipa,
  final_plot_arequipa +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)

biscale_title_arequipa <- ggdraw(
  add_sub(biscale_title_arequipa,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)

biscale_title_arequipa <- ggdraw(
  add_sub(biscale_title_arequipa,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito.", width = 90),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )

ggsave("2. Plots/Ciudades/3. Biscale arequipa provincia.png",
       biscale_title_arequipa,
       device = png,
       width = 8,
       height = 6.4,
       dpi = 300)
```


### Región Piura


```{r}
biscale_piura <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         DEPARTAMENTO == "PIURA") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), lwd = 0,
          color = "white", show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  scale_x_continuous(breaks = rev(seq(-79.2, -81, -0.6))) + 
  annotation_scale(location = "br") +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_piura <- ggdraw(biscale_piura +
                       theme(
                         plot.margin = unit(c(0, 3.5, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_piura <- ggdraw() +
  draw_label(
   "Cobertura y acceso de vacunas contra la COVID-19 \nen Piura",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -8, 0), "cm")
  )

subtitle_piura <- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7.5, 0), "cm")
  )

biscale_title_piura <- plot_grid(
  title_piura, 
  subtitle_piura,
  final_plot_piura +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)

biscale_title_piura <- ggdraw(
  add_sub(biscale_title_piura,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)

biscale_title_piura <- ggdraw(
  add_sub(biscale_title_piura,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )


ggsave("2. Plots/Ciudades/4. Biscale Piura region.png",
       biscale_title_piura,
       device = png,
       width = 6.4,
       height = 7.2,
       dpi = 300)
```


### Región Tacna


```{r}
biscale_tacna <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         DEPARTAMENTO == "TACNA") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), lwd = 0,
          color = "white", show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  annotation_scale() +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_tacna <- ggdraw(biscale_tacna +
                       theme(
                         plot.margin = unit(c(0, 3.5, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_tacna <- ggdraw() +
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19 \nen Tacna",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -8, 0), "cm")
  )

subtitle_tacna<- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7.5, 0), "cm")
  )

biscale_title_tacna <- plot_grid(
  title_tacna, 
  subtitle_tacna,
  final_plot_tacna +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)


biscale_title_tacna <- ggdraw(
  add_sub(biscale_title_tacna,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)

biscale_title_tacna <- ggdraw(
  add_sub(biscale_title_tacna,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )

ggsave("2. Plots/Ciudades/5. Biscale Tacna region.png",
       biscale_title_tacna,
       device = png,
       width = 6.4,
       height = 7.2,
       dpi = 300)
```



### Región Puno


```{r}
biscale_puno <- peru_shp %>%
  mutate(
    ubigeo = str_remove(ubigeo, "AREA # ")
  ) %>% 
  select(-c(reg, prov, distr)) %>% 
  inner_join(
    avance_y_centros 
  ) %>%  
  filter(Grupo_Edad != "12 a 17 años",
         DEPARTAMENTO == "PUNO") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), lwd = 0,
          color = "white", show.legend = FALSE) +
  facet_wrap(vars(Grupo_Edad)) + 
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  scale_x_continuous(breaks = rev(seq(-69, -71, -1))) +
  annotation_scale() +
  # annotation_north_arrow(location = "tr",
  #                        height = unit(0.9, "cm"),
  #                        width = unit(0.7, "cm"),
  #                        style = north_arrow_orienteering) +
  theme_minimal() +
  theme(
    # axis.text = element_blank(),
    # axis.ticks = element_blank(),
    panel.spacing.x = unit(1, "lines"),
    
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    
    # Cuadrícula del fondo
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    # Reafirmar color blanco de fondo
    plot.background = element_rect(fill = "#ffffff", color = NA),
    panel.background = element_rect(fill = "#ffffff", color = NA),
    
    # Facet
    strip.text = element_text(face = "bold",
                              size = 11),
    strip.background = element_rect(fill = "grey85", 
                                    colour = "grey20")
  )
```


```{r}
final_plot_puno <- ggdraw(biscale_puno +
                       theme(
                         plot.margin = unit(c(0, 3, .2, .2), "cm")
                       )) + 
  draw_plot(legend,
            x = 0.75,
            y = 0.35,
            width = 0.27,
            height = 0.27,
            scale = 1) 

title_puno <- ggdraw() +
  draw_label(
    "Cobertura y acceso de vacunas contra la COVID-19 \nen Puno",
    size = 13.5,
    fontface = 'bold',
    x = 0.08,
    y = 0.90,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -10, 0), "cm")
  )

subtitle_puno <- ggdraw() +
  draw_label(
    str_wrap(paste0("Actualizado al ",  fecha_update, "del 2021.")),
    size = 10,
    y = 0.92,
    x = 0.08,
    hjust = 0,
    fontfamily = "Roboto"
  ) +
  theme(
    plot.margin = unit(c(0, 0, -7.5, 0), "cm")
  )

biscale_title_puno <- plot_grid(
  title_puno, 
  subtitle_puno,
  final_plot_puno +
    theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  ),
  ncol = 1,
  rel_heights = c(0.08, 0.08, 1)
)

biscale_title_puno <- ggdraw(
  add_sub(biscale_title_puno,
          "Elaboración: Pendulum - Data Lab",
          size = 12,
          y = 0.65,
          x = 0.95,
          hjust = 1,
          fontfamily = "Inconsolata")
)

biscale_title_puno <- ggdraw(
  add_sub(biscale_title_puno,
          str_wrap("Disponibilidad de centros de vacunación categorizado en 3 grupos: Menos de 1 centro de vacunación, al menos 1 centro de vacunación, más de 2 centros de vacunación por cada 10k de habitantes. Cobertura de vacunación dividido en 3 grupos: 0 a 10%; 10 a 50%; y, 50% a más de la población del distrito."),
          size = 10,
          y = 0.55,
          x = 0.08,
          hjust = 0,
          fontfamily = "Roboto")
) + 
  theme(
    panel.background = element_rect(fill = "white", 
                                    colour = NA)
  )

ggsave("2. Plots/Ciudades/6. Biscale Puno region.png",
       biscale_title_puno,
       device = png,
       width = 6.4,
       height = 9,
       dpi = 300)
```
